apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coomandservice
  template:
    metadata:
      labels:
        app: coomandservice
    spec:
      containers:
        - name: coomandservice
          image: dachimagaria/coomandservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: coomandservice
  ports:
  - name: coomandservice
    protocol: TCP
    port: 80
    targetPort: 80